### ISSUE TITLE
Cannot read property stack of undefined

### ISSUE THREAD

**Issue by jclarkk** [gtramontina/passport-stub#15]
NodeJS ver: 4.2.4
Passport ver: 0.2.1
Express ver: 4.11.0

Error:
    return this.app._router.stack.unshift({
                           ^
TypeError: Cannot read property 'stack' of undefined
  at Object.exports.install (/Users/jonathanclark/WebstormProjects/appcloud-dashboard/node_modules/passport-stub/lib.coffee:15:41)
  at Object.<anonymous> (/Users/jonathanclark/WebstormProjects/appcloud-dashboard/tests/routes/users.test.js:20:14)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at /usr/local/lib/node_modules/mocha/lib/mocha.js:216:27
  at Array.forEach (native)
  at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:213:14)
  at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:453:10)
  at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:393:18)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

**Comment by marianomerlo** [comment]
I'm having the same issue.

**Comment by vincentbriglia** [comment]
You're most likely applying ```stub.install(server);``` on what gets returned from a call like  ```const server = app.listen``` rather than on ```const app = express();```

**Comment by TrejGun** [comment]
for express5 you can do
```
const app = express();
app._router = app.router;
passport.install(app);
```

**Comment by TrejGun** [comment]
https://github.com/TrejGun/passport-stub
